<?php

declare(strict_types=1);

namespace Aurora\Media\Tests\Unit;

use Aurora\Media\Media;
use PHPUnit\Framework\TestCase;

/**
 * @covers \Aurora\Media\Media
 */
final class MediaTest extends TestCase
{
    public function testEntityTypeId(): void
    {
        $media = new Media(['mid' => 1, 'name' => 'Test', 'bundle' => 'image']);

        $this->assertSame('media', $media->getEntityTypeId());
    }

    public function testIdUsesMediaIdKey(): void
    {
        $media = new Media(['mid' => 42, 'name' => 'Test Image', 'bundle' => 'image']);

        $this->assertSame(42, $media->id());
    }

    public function testUuidAutoGenerated(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $this->assertNotEmpty($media->uuid());
    }

    public function testUuidFromConstructor(): void
    {
        $uuid = '550e8400-e29b-41d4-a716-446655440000';
        $media = new Media(['mid' => 1, 'bundle' => 'image', 'uuid' => $uuid]);

        $this->assertSame($uuid, $media->uuid());
    }

    public function testGetAndSetName(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $this->assertSame('', $media->getName());

        $result = $media->setName('Photo of sunset');

        $this->assertSame($media, $result, 'setName() should return $this');
        $this->assertSame('Photo of sunset', $media->getName());
    }

    public function testNameFromConstructor(): void
    {
        $media = new Media(['mid' => 1, 'name' => 'My Video', 'bundle' => 'video']);

        $this->assertSame('My Video', $media->getName());
    }

    public function testLabelReturnsName(): void
    {
        $media = new Media(['mid' => 1, 'name' => 'Logo Image', 'bundle' => 'image']);

        $this->assertSame('Logo Image', $media->label());
    }

    public function testGetBundle(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'document']);

        $this->assertSame('document', $media->getBundle());
        $this->assertSame($media->bundle(), $media->getBundle());
    }

    public function testGetAndSetOwnerId(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $this->assertNull($media->getOwnerId());

        $result = $media->setOwnerId(5);

        $this->assertSame($media, $result);
        $this->assertSame(5, $media->getOwnerId());
    }

    public function testOwnerIdFromConstructor(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image', 'uid' => 10]);

        $this->assertSame(10, $media->getOwnerId());
    }

    public function testIsPublishedDefault(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $this->assertTrue($media->isPublished());
    }

    public function testSetPublished(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $result = $media->setPublished(false);

        $this->assertSame($media, $result);
        $this->assertFalse($media->isPublished());

        $media->setPublished(true);
        $this->assertTrue($media->isPublished());
    }

    public function testPublishedFromConstructor(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image', 'status' => false]);

        $this->assertFalse($media->isPublished());
    }

    public function testGetAndSetCreatedTime(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $this->assertNull($media->getCreatedTime());

        $timestamp = 1700000000;
        $result = $media->setCreatedTime($timestamp);

        $this->assertSame($media, $result);
        $this->assertSame($timestamp, $media->getCreatedTime());
    }

    public function testCreatedTimeFromConstructor(): void
    {
        $timestamp = 1700000000;
        $media = new Media(['mid' => 1, 'bundle' => 'image', 'created' => $timestamp]);

        $this->assertSame($timestamp, $media->getCreatedTime());
    }

    public function testGetAndSetChangedTime(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $this->assertNull($media->getChangedTime());

        $timestamp = 1700001000;
        $result = $media->setChangedTime($timestamp);

        $this->assertSame($media, $result);
        $this->assertSame($timestamp, $media->getChangedTime());
    }

    public function testChangedTimeFromConstructor(): void
    {
        $timestamp = 1700001000;
        $media = new Media(['mid' => 1, 'bundle' => 'image', 'changed' => $timestamp]);

        $this->assertSame($timestamp, $media->getChangedTime());
    }

    public function testIsNew(): void
    {
        $mediaNew = new Media(['bundle' => 'image']);
        $this->assertTrue($mediaNew->isNew());

        $mediaExisting = new Media(['mid' => 1, 'bundle' => 'image']);
        $this->assertFalse($mediaExisting->isNew());
    }

    public function testToArray(): void
    {
        $media = new Media([
            'mid' => 1,
            'name' => 'Test Image',
            'bundle' => 'image',
            'uid' => 5,
            'status' => true,
        ]);

        $array = $media->toArray();

        $this->assertSame(1, $array['mid']);
        $this->assertSame('Test Image', $array['name']);
        $this->assertSame('image', $array['bundle']);
        $this->assertSame(5, $array['uid']);
        $this->assertTrue($array['status']);
        $this->assertArrayHasKey('uuid', $array);
    }

    public function testHasField(): void
    {
        $media = new Media(['mid' => 1, 'name' => 'Test', 'bundle' => 'image']);

        $this->assertTrue($media->hasField('mid'));
        $this->assertTrue($media->hasField('name'));
        $this->assertTrue($media->hasField('bundle'));
        $this->assertFalse($media->hasField('nonexistent'));
    }

    public function testFluentApi(): void
    {
        $media = new Media(['mid' => 1, 'bundle' => 'image']);

        $media->setName('Fluent Image')
            ->setOwnerId(3)
            ->setPublished(true)
            ->setCreatedTime(1700000000)
            ->setChangedTime(1700001000);

        $this->assertSame('Fluent Image', $media->getName());
        $this->assertSame(3, $media->getOwnerId());
        $this->assertTrue($media->isPublished());
        $this->assertSame(1700000000, $media->getCreatedTime());
        $this->assertSame(1700001000, $media->getChangedTime());
    }
}
